import { z } from 'zod';

// Schema para ManifestParcelas
export const manifestParcelasSchema = z.object({
  ID: z.string().optional(),
  manifest_id: z.number().optional(),
  idparcela: z.string().optional(),
  nrciotsistema: z.string().optional(),
  nrciot: z.string().optional(),
  dstipo: z.string().optional(),
  dsstatus: z.string().optional(),
  cdfavorecido: z.string().optional(),
  cdcartafrete: z.string().optional(),
  cdevento: z.string().optional(),
  dtpagto: z.string().nullable().optional(),
  indesconto: z.string().optional(),
  vlbasecalculo: z.number().optional(),
  dtrecebimento: z.string().nullable().optional(),
  vloriginal: z.number().optional(),
  dtinclusao: z.string().nullable().optional(),
  hrinclusao: z.string().optional(),
  dsusuarioinc: z.string().optional(),
  dtreferenciacalculo: z.string().nullable().optional(),
  dsobservacao: z.string().nullable().optional(),
  vlprovisionado: z.number().optional(),
  dtvencimento: z.string().nullable().optional(),
});

// Schema para ManifestFaturamento
export const manifestFaturamentoSchema = z.object({
  ID: z.union([z.string(), z.number()]).optional(),
  manifest_id: z.number().optional(),
  cdempresa: z.string().optional(),
  cdcartafrete: z.string().optional(),
  cdempresaFV: z.string().optional(),
  nrficha: z.string().optional(),
});

// Schema para Manifest (baseado no repositório .NET)
export const manifestSchema = z.object({
  id: z.string().optional(),
  nrciot: z.string(),
  cdempresa: z.string(),
  cdcartafrete: z.string(),
  nrcgccpfprop: z.string(),
  nrcgccpfmot: z.string(),
  dtemissao: z.string().nullable().optional(),
  vlcarga: z.number().nullable().optional(),
  qtpesocarga: z.number().nullable().optional(),
  nrmanifesto: z.string().optional(),
  nrplaca: z.string().optional(),
  nrceporigem: z.string().optional(),
  nrcepdestino: z.string().optional(),
  fgemitida: z.string().optional(),
  dtliberacaopagto: z.string().nullable().optional(),
  cdcentrocusto: z.string().optional(),
  insituacao: z.number().optional(),
  cdcondicaovencto: z.number().optional(),
  dsobservacao: z.string().nullable().optional(),
  cdtipotransporte: z.string().optional(),
  cdremetente: z.string().optional(),
  cddestinatario: z.string().optional(),
  cdnaturezacarga: z.string().optional(),
  cdespeciecarga: z.string().optional(),
  clmercadoria: z.string().optional(),
  qtpeso: z.number().nullable().optional(),
  cdempresaconhec: z.string().optional(),
  nrseqcontrole: z.string().optional(),
  nrnotafiscal: z.string().optional(),
  cdhistorico: z.string().optional(),
  dsusuarioinc: z.string().optional(),
  dsusuariocanc: z.string().nullable().optional(),
  dtinclusao: z.string().nullable().optional(),
  dtcancelamento: z.string().nullable().optional(),
  intipoorigem: z.string().optional(),
  nrplacareboque1: z.string().optional(),
  nrplacareboque2: z.string().optional(),
  nrplacareboque3: z.string().optional(),
  cdtarifa: z.number().optional(),
  dsusuarioacerto: z.string().nullable().optional(),
  dtacerto: z.string().nullable().optional(),
  cdinscricaocomp: z.string().optional(),
  nrseriecomp: z.string().optional(),
  nrcomprovante: z.string().optional(),
  vlfrete: z.number().nullable().optional(),
  insestsenat: z.string().optional(),
  cdmotivocancelamento: z.string().optional(),
  dsobscancelamento: z.string().nullable().optional(),
  inveiculoproprio: z.number().optional(),
  dsusuarioimpressao: z.string().nullable().optional(),
  dtimpressao: z.string().nullable().optional(),
  dtprazomaxentrega: z.string().nullable().optional(),
  nrseloautenticidade: z.string().optional(),
  hrmaxentrega: z.union([z.number(), z.string()]).nullable().optional(),
  cdvinculacaoiss: z.string().optional(),
  dthrretornociot: z.string().nullable().optional(),
  cdciot: z.string().optional(),
  serie: z.number().optional(),
  cdmsgretornociot: z.string().optional(),
  dsmsgretornociot: z.string().nullable().optional(),
  inenvioarquivociot: z.string().optional(),
  dsavisotransportador: z.string().nullable().optional(),
  nrprotocolocancciot: z.string().optional(),
  cdndot: z.string().optional(),
  nrprotocoloautndot: z.string().optional(),
  inoperacaoperiodo: z.string().optional(),
  vlfreteestimado: z.number().nullable().optional(),
  inoperacaodistribuicao: z.number().optional(),
  nrprotocoloenctociot: z.string().optional(),
  indotimpresso: z.string().optional(),
  inveiculo: z.number().optional(),
  cdrota: z.string().optional(),
  inoperadorapagtoctrb: z.string().optional(),
  inrespostaquesttacagreg: z.number().optional(),
  cdmoeda: z.string().optional(),
  nrprotocolointerroociot: z.string().optional(),
  inretimposto: z.string().optional(),
  cdintersenior: z.string().optional(),
  nrcodigooperpagtociot: z.string().optional(),
  cdseqhcm: z.string().optional(),
  insitcalcpedagio: z.string().optional(),
  nrrepom: z.string().optional(),
  vlmanifesto: z.number().nullable().optional(),
  vlcombustivel: z.number().nullable().optional(),
  vlpedagio: z.number().nullable().optional(),
  vlnotacreditodebito: z.number().nullable().optional(),
  vldesconto: z.number().nullable().optional(),
  vlcsll: z.number().nullable().optional(),
  vlpis: z.number().nullable().optional(),
  vlirff: z.number().nullable().optional(),
  vlinss: z.number().nullable().optional(),
  vltotalmanifesto: z.number().nullable().optional(),
  vlabastecimento: z.number().nullable().optional(),
  vladiantamento: z.number().nullable().optional(),
  vlir: z.number().nullable().optional(),
  vlsaldoapagar: z.number().nullable().optional(),
  vlsaldofrete: z.number().nullable().optional(),
  vlcofins: z.number().nullable().optional(),
  vlsestsenat: z.number().nullable().optional(),
  vliss: z.number().nullable().optional(),
  cdtributacao: z.string().optional(),
  vlcsl: z.number().nullable().optional(),
  status: z.string().optional(),
  error_message: z.string().nullable().optional(),
  parcelas: z.array(manifestParcelasSchema).optional(),
  dadosFaturamento: manifestFaturamentoSchema.optional(),
});

// Schema principal para ContasPagarCIOT
export const contasPagarCIOTSchema = z.object({
  cancelado: z.number().nullable().optional(),
  Obscancelado: z.string().nullable().optional(),
  DsUsuarioCan: z.string().nullable().optional(),
  Manifest: manifestSchema,
});

// Schema para cancelamento
export const cancelarContasPagarCIOTSchema = z.object({
  Manifest: z.object({
    nrciot: z.string(),
  }),
  Obscancelado: z.string().nullable().optional(),
  DsUsuarioCan: z.string().nullable().optional(),
});

export type ManifestParcelas = z.infer<typeof manifestParcelasSchema>;
export type ManifestFaturamento = z.infer<typeof manifestFaturamentoSchema>;
export type Manifest = z.infer<typeof manifestSchema>;
export type ContasPagarCIOT = z.infer<typeof contasPagarCIOTSchema>;
export type CancelarContasPagarCIOT = z.infer<typeof cancelarContasPagarCIOTSchema>;
