import { z } from 'zod';

// Esquemas base por tipo de API
export const cteAutorizadoSchema = z.object({
  id: z.number(),
  authorization_number: z.number(),
  status: z.string(),
  xml: z.string(),
  event_xml: z.string().nullable().optional(),
});

export const cteCanceladoSchema = z.object({
  id: z.number(),
  authorization_number: z.number(),
  status: z.string(),
  xml: z.string(),
  event_xml: z.string().nullable().optional(),
});

export const ciotBaseSchema = z.object({
  id: z.string(),
  ciot: z.string(),
  transportadoraCnpj: z.string(),
  criadoEm: z.string(),
});

export const ciotParcelasSchema = z.object({
  id: z.string(),
  nrciot: z.string(),
  cdempresa: z.string(),
  cdcartafrete: z.string(),
  nrcgccpfprop: z.string(),
  tpformapagamentocontratado: z.string(),
  nrformapagamentocontratado: z.string(),
  nrcgccpfmot: z.string(),
  tpformapagamentomotorista: z.string(),
  nrformapagamentomotorista: z.string(),
  tpformapagamentosubcontratado: z.string(),
  nrformapagamentosubcontratado: z.string(),
  dtemissao: z.string(),
  vlcarga: z.number().nullable(),
  qtpesocarga: z.number().nullable(),
  nrmanifesto: z.string(),
  nrplaca: z.string(),
  nrceporigem: z.string(),
  nrcepdestino: z.string(),
  fgemitida: z.number().nullable().optional(),
  dtliberacaopagto: z.string().nullable().optional(),
  cdcentrocusto: z.string().nullable().optional(),
  insituacao: z.number(),
  cdcondicaovencto: z.number(),
  dsobservacao: z.string().nullable().optional(),
  cdtipotransporte: z.string().nullable().optional(),
  cdremetente: z.string(),
  cddestinatario: z.string(),
  cdnaturezacarga: z.string(),
  cdespeciecarga: z.string(),
  clmercadoria: z.string().nullable().optional(),
  qtpeso: z.number().nullable().optional(),
  cdempresaconhec: z.string().nullable().optional(),
  nrseqcontrole: z.string().nullable().optional(),
  nrnotafiscal: z.string(),
  cdhistorico: z.string().nullable().optional(),
  dsusuarioinc: z.string(),
  dsusuariocanc: z.string().nullable().optional(),
  dtinclusao: z.string(),
  dtcancelamento: z.string().nullable().optional(),
  intipoorigem: z.string(),
  nrplacareboque1: z.string(),
  nrplacareboque2: z.string().nullable().optional(),
  nrplacareboque3: z.string().nullable().optional(),
  cdtarifa: z.number(),
  dsusuarioacerto: z.string().nullable().optional(),
  dtacerto: z.string().nullable().optional(),
  cdinscricaocomp: z.string().nullable().optional(),
  nrseriecomp: z.string().nullable().optional(),
  nrcomprovante: z.string().nullable().optional(),
  vlfrete: z.number(),
  insestsenat: z.number().nullable().optional(),
  cdmotivocancelamento: z.string().nullable().optional(),
  dsobscancelamento: z.string().nullable().optional(),
  inveiculoproprio: z.number(),
  dsusuarioimpressao: z.string().nullable().optional(),
  dtimpressao: z.string().nullable().optional(),
  dtprazomaxentrega: z.string(),
  nrseloautenticidade: z.string().nullable().optional(),
  hrmaxentrega: z.string().nullable().optional(),
  cdvinculacaoiss: z.string().nullable().optional(),
  dthrretornociot: z.string().nullable().optional(),
  cdciot: z.string().nullable().optional(),
  serie: z.number(),
  cdmsgretornociot: z.string().nullable().optional(),
  dsmsgretornociot: z.string().nullable().optional(),
  inenvioarquivociot: z.number().nullable().optional(),
  dsavisotransportador: z.string().nullable().optional(),
  nrprotocolocancciot: z.string().nullable().optional(),
  cdndot: z.string().nullable().optional(),
  nrprotocoloautndot: z.string().nullable().optional(),
  inoperacaoperiodo: z.number().nullable().optional(),
  vlfreteestimado: z.number().nullable().optional(),
  inoperacaodistribuicao: z.number(),
  nrprotocoloenctociot: z.string().nullable().optional(),
  indotimpresso: z.string().nullable().optional(),
  inveiculo: z.number(),
  cdrota: z.string(),
  inoperadorapagtoctrb: z.string(),
  inrespostaquesttacagreg: z.number(),
  cdmoeda: z.string().nullable().optional(),
  nrprotocolointerroociot: z.string().nullable().optional(),
  inretimposto: z.string().nullable().optional(),
  cdintersenior: z.string().nullable().optional(),
  nrcodigooperpagtociot: z.string().nullable().optional(),
  cdseqhcm: z.string().nullable().optional(),
  insitcalcpedagio: z.string().nullable().optional(),
  nrrepom: z.string().nullable().optional(),
  vlmanifesto: z.number(),
  vlcombustivel: z.number(),
  vlpedagio: z.number(),
  vlnotacreditodebito: z.number(),
  vldesconto: z.number(),
  vlcsll: z.number(),
  vlpis: z.number(),
  vlirff: z.number(),
  vlinss: z.number(),
  vltotalmanifesto: z.number(),
  vlabastecimento: z.number(),
  vladiantamento: z.number(),
  vlir: z.number(),
  vlsaldoapagar: z.number(),
  vlsaldofrete: z.number(),
  vlcofins: z.number(),
  vlsestsenat: z.number(),
  vliss: z.number(),
  cdtributacao: z.string().nullable().optional(),
  vlcsl: z.number(),
  parcelas: z.array(
    z.object({
      ID: z.string(),
      idparcela: z.string(),
      nrciotsistema: z.string(),
      nrciot: z.string(),
      dstipo: z.string(),
      dsstatus: z.string(),
      cdfavorecido: z.string(),
      cdcartafrete: z.string(),
      cdevento: z.string(),
      dtpagto: z.string(),
      indesconto: z.number().nullable().optional(),
      vlbasecalculo: z.number().nullable().optional(),
      dtrecebimento: z.string().nullable().optional(),
      vloriginal: z.number().nullable().optional(),
      dtinclusao: z.string(),
      hrinclusao: z.string(),
      dsusuarioinc: z.string(),
      dtreferenciacalculo: z.string(),
      dsobservacao: z.string().nullable().optional(),
      vlprovisionado: z.number().nullable().optional(),
    }),
  ),
  dadosFaturamento: z.object({
    ID: z.string(),
    cdempresa: z.string(),
    cdcartafrete: z.string(),
    cdempresaFV: z.string(),
    nrficha: z.string().nullable().optional(),
  }),
});

export const faturaPagarCriarSchema = z.object({
  data: z.object({
    cancelado: z.number().optional(),
    Obscancelado: z.string().optional(),
    id: z.number(),
    type: z.string(),
    document: z.string(),
    issue_date: z.string(),
    due_date: z.string(),
    value: z.string(),
    installment_period: z.string().optional(),
    comments: z.string().optional(),
    corporation: z
      .object({
        id: z.number().optional(),
        person_id: z.number().optional(),
        nickname: z.string().optional(),
        cnpj: z.string().optional(),
      })
      .optional(),
    receiver: z
      .object({
        id: z.number().optional(),
        cpf: z.string().optional(),
        name: z.string().optional(),
        type: z.string().optional(),
      })
      .optional(),
    accounting_planning_management: z
      .object({
        id: z.number().optional(),
        name: z.string().optional(),
      })
      .optional(),
    cost_centers: z.object({ id: z.number().optional(), name: z.string().optional() }).optional(),
    installment_count: z.number().optional(),
    installments: z
      .array(
        z.object({
          id: z.number(),
          position: z.number(),
          due_date: z.string(),
          value: z.string(),
          interest_value: z.string().optional(),
          discount_value: z.string().optional(),
          payment_method: z.string().optional(),
          comments: z.string().optional(),
        }),
      )
      .optional(),
    invoice_items: z.array(z.any()).optional(),
  }),
});

export const faturaPagarBaixarSchema = z.object({
  installment_id: z.number(),
  payment_date: z.string(),
  payment_value: z.number(),
  discount_value: z.number().optional(),
  interest_value: z.number().optional(),
  payment_method: z.string().optional(),
  bank_account: z.string().optional(),
  bankname: z.string().optional(),
  accountnumber: z.string().optional(),
  accountdigit: z.string().optional(),
  comments: z.string().optional(),
});

export const faturaPagarCancelarSchema = z.object({
  id: z.string(),
  numero: z.string(),
  motivo: z.string(),
});

export const faturaReceberCriarSchema = z.object({
  data: z.object({
    cancelado: z.number().optional(),
    Obscancelado: z.string().optional(),
    id: z.number(),
    type: z.string(),
    document: z.string(),
    issue_date: z.string(),
    due_date: z.string(),
    value: z.string(),
    installment_period: z.string().optional(),
    comments: z.string().optional(),
    corporation: z
      .object({
        id: z.number().optional(),
        person_id: z.number().optional(),
        nickname: z.string().optional(),
        cnpj: z.string().optional(),
      })
      .optional(),
    customer: z
      .object({
        id: z.number().optional(),
        cnpj: z.string().optional(),
        name: z.string().optional(),
        type: z.string().optional(),
      })
      .optional(),
    accounting_planning_management: z
      .object({
        id: z.number().optional(),
        name: z.string().optional(),
      })
      .optional(),
    installment_count: z.number().optional(),
    installments: z
      .array(
        z.object({
          id: z.number(),
          position: z.number(),
          due_date: z.string(),
          value: z.string(),
          interest_value: z.string().optional(),
          discount_value: z.string().optional(),
          payment_method: z.string().optional(),
          comments: z.string().optional(),
        }),
      )
      .optional(),
    invoice_items: z
      .array(
        z.object({
          id: z.number(),
          cte_key: z.string().optional(),
          cte_number: z.string().optional(),
          cte_series: z.string().optional(),
          payer_name: z.string().optional(),
          draft_number: z.string().optional(),
          nfse_number: z.string().optional(),
          nfse_series: z.string().optional(),
          total: z.string().optional(),
          type: z.string().optional(),
        }),
      )
      .optional(),
  }),
});

export const faturaReceberBaixarSchema = z.object({
  installment_id: z.number(),
  payment_date: z.string(),
  payment_value: z.number(),
  discount_value: z.number().optional(),
  interest_value: z.number().optional(),
  payment_method: z.string().optional(),
  bank_account: z.string().optional(),
  bankname: z.string().optional(),
  accountnumber: z.string().optional(),
  accountdigit: z.string().optional(),
  comments: z.string().optional(),
});

export const nfseAutorizadoSchema = z.object({
  infNFeCte: z.object({
    numero: z.number(),
    codigoVerificacao: z.string(),
    dataEmissao: z.string(),
    identificacaoRps: z.object({
      numero: z.number(),
      serie: z.string(),
      tipo: z.number(),
    }),
    dataEmissaoRps: z.string(),
    naturezaOperacao: z.number(),
    optanteSimplesNacional: z.number(),
    incentivadorCultural: z.number(),
    competencia: z.string(),
    servico: z.object({
      valores: z.object({
        valorServicos: z.number(),
        valorDeducoes: z.number(),
        issRetido: z.number(),
        valorIss: z.number(),
        valorIssRetido: z.number(),
        baseCalculo: z.number(),
        aliquota: z.number(),
        valorLiquidoNfse: z.number(),
      }),
      itemListaServico: z.number(),
      codigoTributacaoMunicipio: z.string(),
      discriminacao: z.string(),
      codigoMunicipio: z.number(),
    }),
    valorCredito: z.number(),
    prestadorServico: z.object({
      identificacaoPrestador: z.object({
        cnpj: z.string(),
        inscricaoMunicipal: z.string(),
      }),
      razaoSocial: z.string(),
      nomeFantasia: z.string(),
      endereco: z.object({
        logradouro: z.string(),
        numero: z.union([z.number(), z.string()]),
        complemento: z.string(),
        bairro: z.string(),
        codigoMunicipio: z.number(),
        uf: z.string(),
        cep: z.string(),
      }),
      contato: z.object({ telefone: z.string(), email: z.string() }),
    }),
    tomadorServico: z.object({
      identificacaoTomador: z.object({
        cnpj: z.string(),
        inscricaoMunicipal: z.string(),
      }),
      razaoSocial: z.string(),
      endereco: z.object({
        logradouro: z.string(),
        numero: z.union([z.number(), z.string()]),
        complemento: z.string(),
        bairro: z.string(),
        codigoMunicipio: z.number(),
        uf: z.string(),
        cep: z.string(),
      }),
      contato: z.object({ telefone: z.string(), email: z.string() }),
    }),
    orgaoGerador: z.object({ codigoMunicipio: z.number(), uf: z.string() }),
  }),
  dadosLogisticaFrete: z
    .object({
      pesoreal: z.number().optional(),
      pesocubado: z.number().optional(),
      quantidadevolumes: z.number().optional(),
      valorproduto: z.number().optional(),
      valornota: z.number().optional(),
      valorfretepeso: z.number().optional(),
      valoradv: z.number().optional(),
      valoroutros: z.number().optional(),
      comentariofrete: z.string().optional(),
      usuarioalteracao: z.string().optional(),
      datadealteracao: z.string().optional(),
      datacancelamento: z.string().nullable().optional(),
      motivocancelamento: z.string().optional(),
      filialcancelamento: z.string().optional(),
      cnpjConsignatario: z.string().optional(),
      cnpjRedespacho: z.string().optional(),
      cnpjexpedidor: z.string().optional(),
      valorbasecalculopis: z.number().optional(),
      aliqpis: z.number().optional(),
      valorpis: z.number().optional(),
      aliqcofins: z.number().optional(),
      valorcofins: z.number().optional(),
      dataPrazo: z.string().optional(),
      diasentrega: z.number().optional(),
      cnpjRemetente: z.string().optional(),
      cepRemetente: z.string().optional(),
      cnpjDestinatario: z.string().optional(),
      cepDestinatario: z.string().optional(),
      logradouroDestinatario: z.string().optional(),
    })
    .optional(),
});

export const pessoaSchema = z.object({
  codPessoaEsl: z.string(),
  tipoPessoa: z.object({
    codTipoPessoa: z.number(),
    descricao: z.string(),
    lstTipoPessoas: z.array(z.string()).optional(),
  }),
  contatoList: z.array(z.any()).optional(),
  enderecoList: z
    .array(
      z.object({
        tipoEndereco: z.object({
          codTipoEndereco: z.number(),
          descricao: z.string(),
          lstTipoEnderecos: z.array(z.string()).optional(),
        }),
        cep: z.string().nullable().optional(),
        logradouro: z.string().nullable().optional(),
        numero: z.string().nullable().optional(),
        complemento: z.string().nullable().optional(),
        bairro: z.string().nullable().optional(),
        cidade: z.string().nullable().optional(),
        estado: z.string().nullable().optional(),
        lstEnderecos: z.array(z.string()).optional(),
      }),
    )
    .optional(),
  dadosBancarioList: z.array(z.any()).optional(),
  chavesPixList: z.array(z.any()).optional(),
  pessoaPersonagemList: z.array(z.any()).optional(),
  codNaturezaOperacao: z.number().optional(),
  cdFuncionario: z.number().optional(),
  descNaturezaOperacao: z.string().optional(),
  codFilialResponsavel: z.string().optional(),
  descFilialResponsavel: z.string().optional(),
  nomeRazaoSocial: z.string().optional(),
  nomeFantasia: z.string().optional(),
  dataFundacao: z.string().optional(),
  cpf: z.string().optional(),
  cnpj: z.string().optional(),
  rg: z.string().optional(),
  cidadeExpedicaoRG: z.string().optional(),
  orgaoExpedidorRG: z.string().optional(),
  dataEmissaoRG: z.string().optional(),
  sexo: z.boolean().optional(),
  estadoCivil: z.string().optional(),
  dataNascimento: z.string().optional(),
  cidadeNascimento: z.string().optional(),
  inscricaoMunicipal: z.string().optional(),
  inscricaoEstadual: z.string().optional(),
  documentoExterior: z.string().optional(),
  numeroPISPASEP: z.string().optional(),
  rntrc: z.string().optional(),
  dataValidadeRNTRC: z.string().optional(),
  nomePai: z.string().optional(),
  nomeMae: z.string().optional(),
  contrinuinte: z.boolean().optional(),
  site: z.string().optional(),
  codigoCNAE: z.string().optional(),
  regimeFiscal: z.string().optional(),
  codigoSuframa: z.string().optional(),
  observacao: z.string().optional(),
  dataCadastro: z.string().optional(),
  codUsuarioCadastro: z.number().optional(),
  usuarioCadastro: z.string().optional(),
  ativo: z.boolean().optional(),
  flgIntegradoSenior: z.boolean().optional(),
  fgClienteBasico: z.boolean().optional(),
  inLocalDificilEnt: z.boolean().optional(),
  inEmailAdtoViagem: z.boolean().optional(),
  inIntegra: z.boolean().optional(),
  vlPercTDE: z.number().optional(),
  vlMinimoTDE: z.number().optional(),
  inAgeCargaTranspInter: z.boolean().optional(),
  inLocalDificilAcesso: z.boolean().optional(),
  inCarregamentos: z.boolean().optional(),
  inRemetente: z.boolean().optional(),
  inDestinatario: z.boolean().optional(),
  inCliente: z.boolean().optional(),
  inSexo: z.boolean().optional(),
  inRespComercial: z.boolean().optional(),
  inRespColetas: z.boolean().optional(),
  inRespEntregas: z.boolean().optional(),
  inRespFaturamento: z.boolean().optional(),
  inRespEDI: z.boolean().optional(),
  inRespAvarias: z.boolean().optional(),
  inEmailDiaCliente: z.boolean().optional(),
  inEmailFeriados: z.boolean().optional(),
  inEmailInformativo: z.boolean().optional(),
  inEmailCartaoNatal: z.boolean().optional(),
  inEmailProgFinalAno: z.boolean().optional(),
  inEmailComercial: z.boolean().optional(),
  inEmailMarketing: z.boolean().optional(),
  inEmailFaturamento: z.boolean().optional(),
  inEmailOcorrencia: z.boolean().optional(),
  lstPessoas: z.array(z.string()).optional(),
});

export type CteAutorizado = z.infer<typeof cteAutorizadoSchema>;
export type CteCancelado = z.infer<typeof cteCanceladoSchema>;
export type CiotBase = z.infer<typeof ciotBaseSchema>;
export type CiotParcela = z.infer<typeof ciotParcelasSchema>;
export type FaturaPagarCriar = z.infer<typeof faturaPagarCriarSchema>;
export type FaturaPagarBaixar = z.infer<typeof faturaPagarBaixarSchema>;
export type FaturaPagarCancelar = z.infer<typeof faturaPagarCancelarSchema>;
export type FaturaReceberCriar = z.infer<typeof faturaReceberCriarSchema>;
export type FaturaReceberBaixar = z.infer<typeof faturaReceberBaixarSchema>;
export type NfseAutorizado = z.infer<typeof nfseAutorizadoSchema>;
export type Pessoa = z.infer<typeof pessoaSchema>;
