export interface ManifestParcelas {
  ID?: string;
  manifest_id?: number;
  idparcela?: string;
  nrciotsistema?: string;
  nrciot?: string;
  dstipo?: string;
  dsstatus?: string;
  cdfavorecido?: string;
  cdcartafrete?: string;
  cdevento?: string;
  dtpagto?: string | null;
  indesconto?: string | null;
  vlbasecalculo?: number | null;
  dtrecebimento?: string | null;
  vloriginal?: number | null;
  dtinclusao?: string | null;
  hrinclusao?: string | null;
  dsusuarioinc?: string | null;
  dtreferenciacalculo?: string | null;
  dsobservacao?: string | null;
  vlprovisionado?: number | null;
  dtvencimento?: string | null;
}

export interface ManifestFaturamento {
  ID?: string;
  manifest_id?: number;
  cdempresa?: string;
  cdcartafrete?: string;
  cdempresaFV?: string;
  nrficha?: string;
}

export interface Manifest {
  id?: string;
  external_id?: string | number | null;
  nrciot: string;
  cdempresa: string;
  cdcartafrete: string;
  nrcgccpfprop: string;
  nrcgccpfmot: string;
  dtemissao?: string | null;
  vlcarga?: number | null;
  qtpesocarga?: number | null;
  nrmanifesto?: string | null;
  nrplaca?: string | null;
  nrceporigem?: string | null;
  nrcepdestino?: string | null;
  fgemitida?: string | null;
  dtliberacaopagto?: string | null;
  cdcentrocusto?: string | null;
  insituacao?: number | null;
  cdcondicaovencto?: number | null;
  dsobservacao?: string | null;
  cdtipotransporte?: string | null;
  cdremetente?: string | null;
  cddestinatario?: string | null;
  cdnaturezacarga?: string | null;
  cdespeciecarga?: string | null;
  clmercadoria?: string | null;
  qtpeso?: number | null;
  cdempresaconhec?: string | null;
  nrseqcontrole?: string | null;
  nrnotafiscal?: string | null;
  cdhistorico?: string | null;
  dsusuarioinc?: string | null;
  dsusuariocanc?: string | null;
  dtinclusao?: string | null;
  dtcancelamento?: string | null;
  intipoorigem?: string | null;
  nrplacareboque1?: string | null;
  nrplacareboque2?: string | null;
  nrplacareboque3?: string | null;
  cdtarifa?: number | null;
  dsusuarioacerto?: string | null;
  dtacerto?: string | null;
  cdinscricaocomp?: string | null;
  nrseriecomp?: string | null;
  nrcomprovante?: string | null;
  vlfrete?: number | null;
  insestsenat?: string | null;
  cdmotivocancelamento?: string | null;
  dsobscancelamento?: string | null;
  inveiculoproprio?: number | null;
  dsusuarioimpressao?: string | null;
  dtimpressao?: string | null;
  dtprazomaxentrega?: string | null;
  nrseloautenticidade?: string | null;
  hrmaxentrega?: string | number | null;
  cdvinculacaoiss?: string | null;
  dthrretornociot?: string | null;
  cdciot?: string | null;
  serie?: number | null;
  cdmsgretornociot?: string | null;
  dsmsgretornociot?: string | null;
  inenvioarquivociot?: string | null;
  dsavisotransportador?: string | null;
  nrprotocolocancciot?: string | null;
  cdndot?: string | null;
  nrprotocoloautndot?: string | null;
  inoperacaoperiodo?: string | null;
  vlfreteestimado?: number | null;
  inoperacaodistribuicao?: number | null;
  nrprotocoloenctociot?: string | null;
  indotimpresso?: string | null;
  inveiculo?: number | null;
  cdrota?: string | null;
  inoperadorapagtoctrb?: string | null;
  inrespostaquesttacagreg?: number | null;
  cdmoeda?: string | null;
  nrprotocolointerroociot?: string | null;
  inretimposto?: string | null;
  cdintersenior?: string | null;
  nrcodigooperpagtociot?: string | null;
  cdseqhcm?: string | null;
  insitcalcpedagio?: string | null;
  nrrepom?: string | null;
  vlmanifesto?: number | null;
  vlcombustivel?: number | null;
  vlpedagio?: number | null;
  vlnotacreditodebito?: number | null;
  vldesconto?: number | null;
  vlcsll?: number | null;
  vlpis?: number | null;
  vlirff?: number | null;
  vlinss?: number | null;
  vltotalmanifesto?: number | null;
  vlabastecimento?: number | null;
  vladiantamento?: number | null;
  vlir?: number | null;
  vlsaldoapagar?: number | null;
  vlsaldofrete?: number | null;
  vlcofins?: number | null;
  vlsestsenat?: number | null;
  vliss?: number | null;
  cdtributacao?: string | null;
  vlcsl?: number | null;
  status?: string | null;
  error_message?: string | null;
  parcelas?: ManifestParcelas[];
  dadosFaturamento?: ManifestFaturamento;
}

export interface ContasPagarCIOTPayload {
  cancelado?: number | null;
  Obscancelado?: string | null;
  DsUsuarioCan?: string | null;
  Manifest: Manifest;
}
